-- --------------------------------------------------
-- Runtime menu configuration read back from 47.102.130.179 at 2026-06-20 14:41:15 +08:00
-- Generated by scripts/db/export-server-menu-config-to-sql.ps1
-- Keep this file last in deployment SQL lists.
-- RuoYi sys_menu.visible: 0 = show, 1 = hide.
-- --------------------------------------------------

update sys_menu
set visible = case menu_id
    when 1 then '0'
    when 17000 then '0'
    when 17001 then '0'
    when 17002 then '1'
    when 17003 then '1'
    when 17004 then '0'
    when 17005 then '1'
    when 17101 then '0'
    when 17102 then '0'
    when 17103 then '0'
    when 17104 then '0'
    when 17105 then '0'
    when 17106 then '0'
    when 17107 then '0'
    when 17108 then '0'
    when 17109 then '0'
    when 17110 then '0'
    when 17111 then '0'
    when 17112 then '0'
    when 17113 then '0'
    when 17114 then '0'
    when 17115 then '0'
    when 17116 then '0'
    when 17117 then '0'
    when 17201 then '0'
    when 17202 then '0'
    when 17203 then '0'
    when 17204 then '0'
    when 17205 then '0'
    when 17206 then '0'
    when 17207 then '0'
    when 17208 then '0'
    when 17301 then '0'
    when 17302 then '0'
    when 17303 then '0'
    when 17304 then '0'
    when 17305 then '0'
    when 17310 then '0'
    when 17311 then '0'
    when 17312 then '0'
    when 17313 then '0'
    when 17314 then '0'
    when 17320 then '0'
    when 17321 then '0'
    when 17322 then '0'
    when 17323 then '0'
    when 17324 then '0'
    when 17325 then '0'
    when 17330 then '0'
    when 17331 then '0'
    when 17332 then '0'
    when 17333 then '0'
    when 17334 then '0'
    when 17340 then '0'
    when 17350 then '0'
    when 17351 then '0'
    when 17401 then '0'
    when 17402 then '0'
    when 17403 then '0'
    when 17404 then '0'
    when 17405 then '0'
    when 17420 then '0'
    when 17421 then '0'
    when 17422 then '0'
    when 17423 then '0'
    when 17424 then '0'
    when 17425 then '0'
    when 17426 then '0'
    when 17501 then '0'
    when 17502 then '0'
    when 17503 then '0'
    when 17504 then '0'
    when 17505 then '0'
    when 17506 then '0'
    when 17507 then '0'
    when 17600 then '0'
    when 17601 then '0'
    when 17602 then '0'
    when 17603 then '0'
    when 17604 then '0'
    when 17605 then '0'
    when 17606 then '0'
    when 17610 then '0'
    when 17611 then '0'
    when 17612 then '0'
    when 17613 then '0'
    when 17620 then '0'
    when 17621 then '0'
    when 17622 then '0'
    when 17630 then '1'
    when 17631 then '1'
    when 17632 then '1'
    when 17640 then '0'
    when 17641 then '0'
    when 17642 then '0'
    when 17700 then '0'
    when 17701 then '0'
    when 17702 then '0'
    when 17703 then '0'
    when 17800 then '0'
    when 17801 then '0'
    when 17802 then '0'
    when 17900 then '0'
    when 17901 then '0'
    when 17902 then '0'
    when 17903 then '0'
    when 17904 then '0'
    when 17905 then '0'
    when 17920 then '0'
    when 17921 then '0'
    when 17922 then '0'
    when 17923 then '0'
    when 17930 then '0'
    when 17931 then '0'
    when 17932 then '0'
    when 17940 then '0'
    when 17941 then '0'
    when 17942 then '0'
    when 17943 then '0'
    when 17944 then '0'
    when 17945 then '0'
    when 17946 then '0'
    when 17947 then '0'
    when 17948 then '0'
    when 17949 then '0'
    when 17950 then '0'
    when 17980 then '0'
    when 17981 then '0'
    when 17982 then '0'
    when 17983 then '0'
    when 17984 then '0'
    when 17985 then '0'
    when 17986 then '0'
    when 17990 then '0'
    when 17991 then '0'
    when 17992 then '0'
    when 17993 then '0'
    when 17994 then '0'
    when 17995 then '0'
    when 18000 then '0'
    when 18001 then '0'
    when 18002 then '0'
    when 18010 then '0'
    when 18011 then '0'
    when 18012 then '0'
    when 18013 then '0'
    else visible
end,
    status = case menu_id
    when 1 then '0'
    when 17000 then '0'
    when 17001 then '0'
    when 17002 then '0'
    when 17003 then '0'
    when 17004 then '0'
    when 17005 then '0'
    when 17101 then '0'
    when 17102 then '0'
    when 17103 then '0'
    when 17104 then '0'
    when 17105 then '0'
    when 17106 then '0'
    when 17107 then '0'
    when 17108 then '0'
    when 17109 then '0'
    when 17110 then '0'
    when 17111 then '0'
    when 17112 then '0'
    when 17113 then '0'
    when 17114 then '0'
    when 17115 then '0'
    when 17116 then '0'
    when 17117 then '0'
    when 17201 then '0'
    when 17202 then '0'
    when 17203 then '0'
    when 17204 then '0'
    when 17205 then '0'
    when 17206 then '0'
    when 17207 then '0'
    when 17208 then '0'
    when 17301 then '0'
    when 17302 then '0'
    when 17303 then '0'
    when 17304 then '0'
    when 17305 then '0'
    when 17310 then '0'
    when 17311 then '0'
    when 17312 then '0'
    when 17313 then '0'
    when 17314 then '0'
    when 17320 then '0'
    when 17321 then '0'
    when 17322 then '0'
    when 17323 then '0'
    when 17324 then '0'
    when 17325 then '0'
    when 17330 then '0'
    when 17331 then '0'
    when 17332 then '0'
    when 17333 then '0'
    when 17334 then '0'
    when 17340 then '0'
    when 17350 then '0'
    when 17351 then '0'
    when 17401 then '0'
    when 17402 then '0'
    when 17403 then '0'
    when 17404 then '0'
    when 17405 then '0'
    when 17420 then '0'
    when 17421 then '0'
    when 17422 then '0'
    when 17423 then '0'
    when 17424 then '0'
    when 17425 then '0'
    when 17426 then '0'
    when 17501 then '0'
    when 17502 then '0'
    when 17503 then '0'
    when 17504 then '0'
    when 17505 then '0'
    when 17506 then '0'
    when 17507 then '0'
    when 17600 then '0'
    when 17601 then '0'
    when 17602 then '0'
    when 17603 then '0'
    when 17604 then '0'
    when 17605 then '0'
    when 17606 then '0'
    when 17610 then '0'
    when 17611 then '0'
    when 17612 then '0'
    when 17613 then '0'
    when 17620 then '0'
    when 17621 then '0'
    when 17622 then '0'
    when 17630 then '1'
    when 17631 then '1'
    when 17632 then '1'
    when 17640 then '0'
    when 17641 then '0'
    when 17642 then '0'
    when 17700 then '0'
    when 17701 then '0'
    when 17702 then '0'
    when 17703 then '0'
    when 17800 then '0'
    when 17801 then '0'
    when 17802 then '0'
    when 17900 then '0'
    when 17901 then '0'
    when 17902 then '0'
    when 17903 then '0'
    when 17904 then '0'
    when 17905 then '0'
    when 17920 then '0'
    when 17921 then '0'
    when 17922 then '0'
    when 17923 then '0'
    when 17930 then '0'
    when 17931 then '0'
    when 17932 then '0'
    when 17940 then '0'
    when 17941 then '0'
    when 17942 then '0'
    when 17943 then '0'
    when 17944 then '0'
    when 17945 then '0'
    when 17946 then '0'
    when 17947 then '0'
    when 17948 then '0'
    when 17949 then '0'
    when 17950 then '0'
    when 17980 then '0'
    when 17981 then '0'
    when 17982 then '0'
    when 17983 then '0'
    when 17984 then '0'
    when 17985 then '0'
    when 17986 then '0'
    when 17990 then '0'
    when 17991 then '0'
    when 17992 then '0'
    when 17993 then '0'
    when 17994 then '0'
    when 17995 then '0'
    when 18000 then '0'
    when 18001 then '0'
    when 18002 then '0'
    when 18010 then '0'
    when 18011 then '0'
    when 18012 then '0'
    when 18013 then '0'
    else status
end,
    update_time = sysdate()
where menu_id in (1, 17000, 17001, 17002, 17003, 17004, 17005, 17101, 17102, 17103, 17104, 17105, 17106, 17107, 17108, 17109, 17110, 17111, 17112, 17113, 17114, 17115, 17116, 17117, 17201, 17202, 17203, 17204, 17205, 17206, 17207, 17208, 17301, 17302, 17303, 17304, 17305, 17310, 17311, 17312, 17313, 17314, 17320, 17321, 17322, 17323, 17324, 17325, 17330, 17331, 17332, 17333, 17334, 17340, 17350, 17351, 17401, 17402, 17403, 17404, 17405, 17420, 17421, 17422, 17423, 17424, 17425, 17426, 17501, 17502, 17503, 17504, 17505, 17506, 17507, 17600, 17601, 17602, 17603, 17604, 17605, 17606, 17610, 17611, 17612, 17613, 17620, 17621, 17622, 17630, 17631, 17632, 17640, 17641, 17642, 17700, 17701, 17702, 17703, 17800, 17801, 17802, 17900, 17901, 17902, 17903, 17904, 17905, 17920, 17921, 17922, 17923, 17930, 17931, 17932, 17940, 17941, 17942, 17943, 17944, 17945, 17946, 17947, 17948, 17949, 17950, 17980, 17981, 17982, 17983, 17984, 17985, 17986, 17990, 17991, 17992, 17993, 17994, 17995, 18000, 18001, 18002, 18010, 18011, 18012, 18013);

-- Reconcile menu grants for the art roles that drive the user-visible menu.
delete rm
from sys_role_menu rm
join sys_role r on r.role_id = rm.role_id
where r.role_key in ('crehn_admin', 'crehn_school', 'crehn_auditor', 'crehn_reviewer', 'crehn_project_viewer')
  and (rm.menu_id between 17000 and 18999 or rm.menu_id in (1));

insert ignore into sys_role_menu(role_id, menu_id)
select r.role_id, v.menu_id
from (
    select 'crehn_admin' as role_key, 1 as menu_id union all
    select 'crehn_admin' as role_key, 17000 as menu_id union all
    select 'crehn_admin' as role_key, 17001 as menu_id union all
    select 'crehn_admin' as role_key, 17002 as menu_id union all
    select 'crehn_admin' as role_key, 17003 as menu_id union all
    select 'crehn_admin' as role_key, 17004 as menu_id union all
    select 'crehn_admin' as role_key, 17005 as menu_id union all
    select 'crehn_admin' as role_key, 17101 as menu_id union all
    select 'crehn_admin' as role_key, 17102 as menu_id union all
    select 'crehn_admin' as role_key, 17103 as menu_id union all
    select 'crehn_admin' as role_key, 17104 as menu_id union all
    select 'crehn_admin' as role_key, 17105 as menu_id union all
    select 'crehn_admin' as role_key, 17106 as menu_id union all
    select 'crehn_admin' as role_key, 17107 as menu_id union all
    select 'crehn_admin' as role_key, 17108 as menu_id union all
    select 'crehn_admin' as role_key, 17109 as menu_id union all
    select 'crehn_admin' as role_key, 17110 as menu_id union all
    select 'crehn_admin' as role_key, 17111 as menu_id union all
    select 'crehn_admin' as role_key, 17112 as menu_id union all
    select 'crehn_admin' as role_key, 17113 as menu_id union all
    select 'crehn_admin' as role_key, 17114 as menu_id union all
    select 'crehn_admin' as role_key, 17115 as menu_id union all
    select 'crehn_admin' as role_key, 17116 as menu_id union all
    select 'crehn_admin' as role_key, 17117 as menu_id union all
    select 'crehn_admin' as role_key, 17201 as menu_id union all
    select 'crehn_admin' as role_key, 17202 as menu_id union all
    select 'crehn_admin' as role_key, 17203 as menu_id union all
    select 'crehn_admin' as role_key, 17204 as menu_id union all
    select 'crehn_admin' as role_key, 17205 as menu_id union all
    select 'crehn_admin' as role_key, 17206 as menu_id union all
    select 'crehn_admin' as role_key, 17207 as menu_id union all
    select 'crehn_admin' as role_key, 17208 as menu_id union all
    select 'crehn_admin' as role_key, 17305 as menu_id union all
    select 'crehn_admin' as role_key, 17401 as menu_id union all
    select 'crehn_admin' as role_key, 17402 as menu_id union all
    select 'crehn_admin' as role_key, 17403 as menu_id union all
    select 'crehn_admin' as role_key, 17404 as menu_id union all
    select 'crehn_admin' as role_key, 17405 as menu_id union all
    select 'crehn_admin' as role_key, 17420 as menu_id union all
    select 'crehn_admin' as role_key, 17421 as menu_id union all
    select 'crehn_admin' as role_key, 17422 as menu_id union all
    select 'crehn_admin' as role_key, 17423 as menu_id union all
    select 'crehn_admin' as role_key, 17424 as menu_id union all
    select 'crehn_admin' as role_key, 17425 as menu_id union all
    select 'crehn_admin' as role_key, 17426 as menu_id union all
    select 'crehn_admin' as role_key, 17501 as menu_id union all
    select 'crehn_admin' as role_key, 17502 as menu_id union all
    select 'crehn_admin' as role_key, 17503 as menu_id union all
    select 'crehn_admin' as role_key, 17504 as menu_id union all
    select 'crehn_admin' as role_key, 17505 as menu_id union all
    select 'crehn_admin' as role_key, 17506 as menu_id union all
    select 'crehn_admin' as role_key, 17507 as menu_id union all
    select 'crehn_admin' as role_key, 17610 as menu_id union all
    select 'crehn_admin' as role_key, 17611 as menu_id union all
    select 'crehn_admin' as role_key, 17612 as menu_id union all
    select 'crehn_admin' as role_key, 17613 as menu_id union all
    select 'crehn_admin' as role_key, 17620 as menu_id union all
    select 'crehn_admin' as role_key, 17621 as menu_id union all
    select 'crehn_admin' as role_key, 17622 as menu_id union all
    select 'crehn_admin' as role_key, 17640 as menu_id union all
    select 'crehn_admin' as role_key, 17641 as menu_id union all
    select 'crehn_admin' as role_key, 17642 as menu_id union all
    select 'crehn_admin' as role_key, 17700 as menu_id union all
    select 'crehn_admin' as role_key, 17701 as menu_id union all
    select 'crehn_admin' as role_key, 17702 as menu_id union all
    select 'crehn_admin' as role_key, 17703 as menu_id union all
    select 'crehn_admin' as role_key, 17800 as menu_id union all
    select 'crehn_admin' as role_key, 17801 as menu_id union all
    select 'crehn_admin' as role_key, 17802 as menu_id union all
    select 'crehn_admin' as role_key, 17900 as menu_id union all
    select 'crehn_admin' as role_key, 17901 as menu_id union all
    select 'crehn_admin' as role_key, 17902 as menu_id union all
    select 'crehn_admin' as role_key, 17903 as menu_id union all
    select 'crehn_admin' as role_key, 17904 as menu_id union all
    select 'crehn_admin' as role_key, 17905 as menu_id union all
    select 'crehn_admin' as role_key, 17930 as menu_id union all
    select 'crehn_admin' as role_key, 17931 as menu_id union all
    select 'crehn_admin' as role_key, 17932 as menu_id union all
    select 'crehn_admin' as role_key, 17940 as menu_id union all
    select 'crehn_admin' as role_key, 17941 as menu_id union all
    select 'crehn_admin' as role_key, 17942 as menu_id union all
    select 'crehn_admin' as role_key, 17943 as menu_id union all
    select 'crehn_admin' as role_key, 17944 as menu_id union all
    select 'crehn_admin' as role_key, 17945 as menu_id union all
    select 'crehn_admin' as role_key, 17946 as menu_id union all
    select 'crehn_admin' as role_key, 17947 as menu_id union all
    select 'crehn_admin' as role_key, 17948 as menu_id union all
    select 'crehn_admin' as role_key, 17949 as menu_id union all
    select 'crehn_admin' as role_key, 17950 as menu_id union all
    select 'crehn_admin' as role_key, 17980 as menu_id union all
    select 'crehn_admin' as role_key, 17981 as menu_id union all
    select 'crehn_admin' as role_key, 17982 as menu_id union all
    select 'crehn_admin' as role_key, 17983 as menu_id union all
    select 'crehn_admin' as role_key, 17984 as menu_id union all
    select 'crehn_admin' as role_key, 17985 as menu_id union all
    select 'crehn_admin' as role_key, 17986 as menu_id union all
    select 'crehn_admin' as role_key, 17990 as menu_id union all
    select 'crehn_admin' as role_key, 17991 as menu_id union all
    select 'crehn_admin' as role_key, 17992 as menu_id union all
    select 'crehn_admin' as role_key, 18000 as menu_id union all
    select 'crehn_admin' as role_key, 18001 as menu_id union all
    select 'crehn_admin' as role_key, 18002 as menu_id union all
    select 'crehn_admin' as role_key, 18010 as menu_id union all
    select 'crehn_admin' as role_key, 18011 as menu_id union all
    select 'crehn_admin' as role_key, 18012 as menu_id union all
    select 'crehn_admin' as role_key, 18013 as menu_id union all
    select 'crehn_auditor' as role_key, 17000 as menu_id union all
    select 'crehn_auditor' as role_key, 17004 as menu_id union all
    select 'crehn_auditor' as role_key, 17401 as menu_id union all
    select 'crehn_auditor' as role_key, 17402 as menu_id union all
    select 'crehn_auditor' as role_key, 17403 as menu_id union all
    select 'crehn_auditor' as role_key, 17404 as menu_id union all
    select 'crehn_auditor' as role_key, 17405 as menu_id union all
    select 'crehn_auditor' as role_key, 17940 as menu_id union all
    select 'crehn_auditor' as role_key, 17941 as menu_id union all
    select 'crehn_auditor' as role_key, 17947 as menu_id union all
    select 'crehn_auditor' as role_key, 17950 as menu_id union all
    select 'crehn_project_viewer' as role_key, 17000 as menu_id union all
    select 'crehn_project_viewer' as role_key, 17980 as menu_id union all
    select 'crehn_project_viewer' as role_key, 17981 as menu_id union all
    select 'crehn_project_viewer' as role_key, 17983 as menu_id union all
    select 'crehn_project_viewer' as role_key, 17985 as menu_id union all
    select 'crehn_school' as role_key, 17000 as menu_id union all
    select 'crehn_school' as role_key, 17003 as menu_id union all
    select 'crehn_school' as role_key, 17301 as menu_id union all
    select 'crehn_school' as role_key, 17302 as menu_id union all
    select 'crehn_school' as role_key, 17303 as menu_id union all
    select 'crehn_school' as role_key, 17304 as menu_id union all
    select 'crehn_school' as role_key, 17305 as menu_id union all
    select 'crehn_school' as role_key, 17311 as menu_id union all
    select 'crehn_school' as role_key, 17312 as menu_id union all
    select 'crehn_school' as role_key, 17313 as menu_id union all
    select 'crehn_school' as role_key, 17314 as menu_id union all
    select 'crehn_school' as role_key, 17320 as menu_id union all
    select 'crehn_school' as role_key, 17321 as menu_id union all
    select 'crehn_school' as role_key, 17322 as menu_id union all
    select 'crehn_school' as role_key, 17323 as menu_id union all
    select 'crehn_school' as role_key, 17324 as menu_id union all
    select 'crehn_school' as role_key, 17325 as menu_id union all
    select 'crehn_school' as role_key, 17330 as menu_id union all
    select 'crehn_school' as role_key, 17331 as menu_id union all
    select 'crehn_school' as role_key, 17332 as menu_id union all
    select 'crehn_school' as role_key, 17333 as menu_id union all
    select 'crehn_school' as role_key, 17334 as menu_id union all
    select 'crehn_school' as role_key, 17340 as menu_id union all
    select 'crehn_school' as role_key, 17350 as menu_id union all
    select 'crehn_school' as role_key, 17351 as menu_id union all
    select 'crehn_school' as role_key, 17800 as menu_id union all
    select 'crehn_school' as role_key, 17801 as menu_id union all
    select 'crehn_school' as role_key, 17802 as menu_id
) v
join sys_role r on r.role_key = v.role_key
join sys_menu m on m.menu_id = v.menu_id;

update sys_menu
set visible = '1',
    status = '1',
    perms = '',
    component = '',
    remark = '已退役：旧名额规则入口已合并到当前活动规则'
where menu_id = 17630;

update sys_menu
set visible = '1',
    status = '1',
    perms = '',
    remark = '已退役：旧名额规则按钮权限不再使用'
where menu_id in (17631, 17632);

delete from sys_role_menu where menu_id in (17630, 17631, 17632);
