-- Schema-only compatibility for DYZ home-configuration packages.
-- No DYZ portal content, menu, activity, user, or style data is copied.

create table if not exists home_site_config (
    id bigint not null,
    tenant_id varchar(20) default '000000',
    config_code varchar(64) not null,
    site_name varchar(128) not null,
    logo_oss_id bigint default null,
    logo_url varchar(500) default null,
    home_link varchar(255) default '#home',
    nav_items_json text default null,
    header_buttons_json text default null,
    login_state_config_json text default null,
    section_config_json text default null,
    notice_limit int default 6,
    footer_title varchar(128) default null,
    footer_text varchar(500) default null,
    organizer varchar(255) default null,
    sponsor varchar(255) default null,
    technical_support varchar(255) default null,
    contact_phone varchar(64) default null,
    contact_email varchar(128) default null,
    contact_address varchar(255) default null,
    icp_text varchar(128) default null,
    icp_link varchar(255) default null,
    police_text varchar(128) default null,
    police_link varchar(255) default null,
    custom_css text default null,
    enabled tinyint(1) default 1,
    remark varchar(500) default null,
    create_dept bigint default null, create_by bigint default null, create_time datetime default null,
    update_by bigint default null, update_time datetime default null, del_flag char(1) default '0',
    primary key (id),
    unique key uk_home_site_config_code (config_code)
) engine=innodb comment='DYZ package compatible home site configuration';

create table if not exists home_content_card (
    id bigint not null,
    tenant_id varchar(20) default '000000',
    section_key varchar(32) not null,
    card_code varchar(64) not null,
    card_type varchar(32) default 'info',
    card_title varchar(128) not null,
    card_subtitle varchar(255) default null,
    card_content text default null,
    icon varchar(64) default null,
    image_oss_id bigint default null,
    image_url varchar(500) default null,
    link_text varchar(64) default null,
    link_url varchar(255) default null,
    link_type varchar(32) default 'anchor',
    highlight tinyint(1) default 0,
    enabled tinyint(1) default 1,
    sort_order int default 0,
    layout_type varchar(32) default 'default',
    template_code varchar(64) default null,
    slot_key varchar(64) default null,
    config_json text default null,
    remark varchar(500) default null,
    create_dept bigint default null, create_by bigint default null, create_time datetime default null,
    update_by bigint default null, update_time datetime default null, del_flag char(1) default '0',
    primary key (id),
    unique key uk_home_content_card_code (card_code),
    key idx_home_content_card_section (section_key, enabled, sort_order)
) engine=innodb comment='DYZ package compatible home content card';

create table if not exists home_page_module (
    id bigint not null,
    tenant_id varchar(20) default '000000',
    module_code varchar(64) not null,
    module_title varchar(128) not null,
    module_type varchar(32) default 'custom',
    anchor varchar(64) default null,
    eyebrow varchar(128) default null,
    intro varchar(500) default null,
    more_text varchar(128) default null,
    more_link varchar(255) default null,
    nav_enabled tinyint(1) default 1,
    enabled tinyint(1) default 1,
    sort_order int default 0,
    layout_type varchar(32) default 'default',
    template_code varchar(64) default null,
    config_json text default null,
    remark varchar(500) default null,
    create_dept bigint default null, create_by bigint default null, create_time datetime default null,
    update_by bigint default null, update_time datetime default null, del_flag char(1) default '0',
    primary key (id),
    unique key uk_home_page_module_code (tenant_id, module_code),
    key idx_home_page_module_sort (tenant_id, enabled, sort_order)
) engine=innodb comment='DYZ package compatible home page module';
